# Generated by Django 4.0.4 on 2022-04-19 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='제목')),
                ('category', models.CharField(choices=[('General', '일반'), ('Account', '계정'), ('Etc', '기타')], default='General', max_length=7, verbose_name='카테고리')),
                ('e_mail', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('e_mail_check', models.BooleanField(verbose_name='이메일수신동의')),
                ('phone_number', models.CharField(blank=True, max_length=12, verbose_name='전화번호')),
                ('phone_number_check', models.BooleanField(verbose_name='이메일수신동의')),
                ('content', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
